import { prisma } from './_db.server'

export const getSEOs = async (): Promise<{ seo: typeof seo }> => {
	const seo = await prisma.seo.findMany({
		include: {
			Post: {
				select: {
					slug: true,
				},
			},
		},
	})
	return { seo }
}

export const getSEO = async (route: string): Promise<{ seo: typeof seo }> => {
	const seo = await prisma.seo.findFirst({
		where: { route },
	})
	return { seo }
}

export const createSEO = async (props: {
	route: string
	title: string
	description: string
	autoGenerated: boolean
}): Promise<{ seo: typeof seo }> => {
	const { route, title, description, autoGenerated } = props

	const seo = await prisma.seo.create({
		data: {
			route,
			title,
			description,
			autoGenerated: autoGenerated,
		},
	})
	return { seo }
}

export const updateSEO = async (props: {
	id: string
	title: string
	description: string
}): Promise<{ seo: typeof seo }> => {
	const { id, title, description } = props

	const seo = await prisma.seo.update({
		where: { id },
		data: {
			title,
			description,
		},
	})
	return { seo }
}

export const deleteSEO = async (id: string): Promise<{ seo: typeof seo }> => {
	const seo = await prisma.seo.delete({
		where: { id },
	})
	return { seo }
}
